{{- $profile := include "tomcat-app.profile" . | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tomcat-app.fullname" . }}-secrets
  labels:
    app: {{ include "tomcat-app.name" . }}
    profile: {{ .Values.profile }}
type: Opaque
data:
  # SSL/TLS secrets - using actual keystore password
  keystore-password: {{ "tomcat" | b64enc }}
  
  # Probe credentials - using actual credentials from Dockerfile
  probe-username: {{ "admin" | b64enc }}
  probe-password: {{ "probe" | b64enc }}